apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-07-05T03:15:29Z","name":"gocd-server","namespace":"default","resourceVersion":"20090","uid":"e83a1102-b586-42ee-8b58-f9876674978b"},"spec":{"clusterIP":"10.100.101.219","clusterIPs":["10.100.101.219"],"externalTrafficPolicy":"Cluster","ports":[{"nodePort":32492,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"run":"gocd-server"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2021-07-05T04:43:32Z"
  name: gocd-server
  namespace: default
  resourceVersion: "22850"
spec:
  clusterIP: 10.100.101.219
  clusterIPs:
  - 10.100.101.219
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32492
    port: 8080
    protocol: TCP
    targetPort: 8153
  selector:
    run: gocd-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
